In [6]:
import pandas as pd
import numpy as np
from sklearn import linear_model



df = pd.read_csv('homeprices.csv')
df


area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [16]:
values = linear_model.LinearRegression()
values.fit(df[['area']], df.price)

LinearRegression()

In [66]:
values.predict([[5000]])

array([859554.79452055])

In [17]:
values.coef_

array([135.78767123])

In [18]:
values.intercept_

180616.43835616432

In [82]:
import pickle
with open('modeel_pickle','wb') as f:
    pickle.dump(df,f)

In [103]:
with open('modeel_pickle', 'rb') as f:
    np = pickle.load(f)
np

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [100]:
re_nf = linear_model.LinearRegression()
re_nf.fit(nf[['area']], nf.price)

LinearRegression()

In [101]:
re_nf.predict([[2000]])

array([452191.78082192])

In [44]:
import joblib

joblib.dump(df,'modeel_joblib')

['modeel_joblib']

In [70]:
nf = joblib.load('modeel_joblib')
nf

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [75]:
pre_nf = linear_model.LinearRegression()
pre_nf.fit(nf[['area']], nf.price)

LinearRegression()

In [76]:
pre_nf.predict([[2000]])

array([452191.78082192])

In [77]:
pre_nf.coef_

array([135.78767123])