In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)


**Logistic Regression.**

In [6]:
model = LogisticRegression()
model.fit(x_train,y_train)


C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [7]:
model.score(x_test,y_test)

0.975925925925926

**Linear Regression.**

In [8]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)


LinearRegression()

In [13]:
model.score(x_test,y_test)

0.586734593617522

**SVM.**

In [14]:
model = SVC()
model.fit(x_train,y_train)

SVC()

In [15]:
model.score(x_test,y_test)

0.9925925925925926

**Random Forest Classifier.**

In [18]:
model.score(x_test,y_test)

0.975925925925926

**Decision Tree Classifier.**

In [19]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train,y_train)


DecisionTreeClassifier()

In [20]:
model.score(x_test,y_test)

0.8648148148148148

# Kfold cross validation

**Basic exmaple using 3 folds.**

In [36]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [37]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [45]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [46]:
get_score(SVC(), x_train,x_test, y_train, y_test)

0.9925925925925926

**StratifiedKFold.**

In [47]:
from sklearn.model_selection import StratifiedKFold
sk = StratifiedKFold(n_splits=3)


In [71]:
score_l = []
scores_svm = []
score_randf = []

for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    score_l.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    score_randf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [72]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [73]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [74]:
score_randf

[0.9282136894824707, 0.9515859766277128, 0.9198664440734557]

<h2 style='color:purple'>cross_val_score function</h2>

In [77]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [78]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [80]:
cross_val_score(LinearRegression(), digits.data, digits.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [79]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93333333, 0.91666667, 0.96100279, 0.9637883 , 0.93036212])

In [81]:
cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target)

array([0.91388889, 0.90833333, 0.95264624, 0.95543175, 0.93036212])

In [82]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.86388889, 0.81388889, 0.91086351, 0.87743733, 0.85793872])

In [83]:
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target)

array([0.9       , 0.875     , 0.95821727, 0.96935933, 0.89693593])